strimzi:
  enabled: true

imagePullSecrets:
  - name: ${image_pull_secret_name}

serviceAccount:
  name: nebuly
  create: true
  annotations:
    eks.amazonaws.com/role-arn: ${eks_iam_role_arn}

# Cert-manager issuer.
# Remove this section if you're not using cert-manager for SSL certificates.
clusterIssuer:
  enabled: true
  name: letsencrypt
  email: support@nebuly.ai

backend:
  image:
    repository: "ghcr.io/nebuly-ai/nebuly-backend"
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
      # ------------
      # Cert-manager issuer.
      # Remove this section if you're not using cert-manager for SSL certificates.
      cert-manager.io/cluster-issuer: letsencrypt
      # ------------
    enabled: true
    className: "nginx"
    hosts:
      - host: ${platform_domain}
        paths:
          - path: /backend(/|$)(.*)
            pathType: Prefix
    tls:
      - secretName: nebuly-tls
        hosts:
          - ${platform_domain}

  volumeMounts:
    - name: secrets-store
      mountPath: /mnt/secrets-store
      readOnly: true
  volumes:
    - name: secrets-store
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: ${secret_provider_class_name}

eventIngestion:
  image:
    repository: "ghcr.io/nebuly-ai/nebuly-event-ingestion"

  rootPath: "/event-ingestion"

  ingress:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
      # ------------
      # Cert-manager issuer.
      # Remove this section if you're not using cert-manager for SSL certificates.
      cert-manager.io/cluster-issuer: letsencrypt
      # ------------
    enabled: true
    className: "nginx"
    hosts:
      - host: ${platform_domain}
        paths:
          - path: /event-ingestion(/|$)(.*)
            pathType: Prefix
    tls:
      - secretName: nebuly-tls
        hosts:
          - ${platform_domain}

aiModels:
  registry: aws_s3
  aws:
    bucketName: ${s3_bucket_name}

  sync:
    enabled: true
    source:
      existingSecret:
        name: ${secret_provider_class_secret_name}
        clientIdKey: ${k8s_secret_key_nebuly_client_id}
        clientSecretKey: ${k8s_secret_key_nebuly_client_secret}

ingestionWorker:
  image:
    repository: "ghcr.io/nebuly-ai/nebuly-ingestion-worker"

  volumeMounts:
    - name: secrets-store
      mountPath: /mnt/secrets-store
      readOnly: true
  volumes:
    - name: secrets-store
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: ${secret_provider_class_name}


primaryProcessing:
  schedule: "0 23 * * *" # Every day at 11:00 PM, cluster's timezone
  hostIPC: true
  resources:
    requests:
      cpu: 1
    limits:
      nvidia.com/gpu: 4

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nebuly.com/accelerator
                operator: In
                values:
                  - nvidia-ampere-a10
  tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists

secondaryProcessing:
  schedule: "0 2 * * *" # Every day at 2:00 AM, cluster's timezone

  tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists


kafka:
  external: false
  zookeeper:
    replicas: 1
    storage:
      class: gp3-csi
  replicas: 1
  config:
    offsets.topic.replication.factor: 1
    replica.selector.class: org.apache.kafka.common.replica.RackAwareReplicaSelector
  storage:
    class: gp3-csi
    size: 32Gi
  resources:
    limits:
      memory: 6Gi
    requests:
      memory: 6Gi

analyticDatabase:
  server: "${analytics_postgres_server_url}"
  name: ${analytics_postgres_db_name}
  existingSecret:
    name: ${secret_provider_class_secret_name}
    userKey: ${k8s_secret_key_analytics_db_username}
    passwordKey: ${k8s_secret_key_analytics_db_password}

auth:
  image:
    repository: "ghcr.io/nebuly-ai/nebuly-tenant-registry"

  postgresServer: "${auth_postgres_server_url}"
  postgresDatabase: ${auth_postgres_db_name}
  existingSecret:
    name: ${secret_provider_class_secret_name}
    postgresUserKey: ${k8s_secret_key_auth_db_username}
    postgresPasswordKey: ${k8s_secret_key_auth_db_password}
    jwtSigningKey: ${k8s_secret_key_jwt_signing_key}

  %{ if okta_sso_enabled }
  loginModes: "okta"
  %{ endif }
  %{ if google_sso_enabled }
  loginModes: "google"
  %{ else }
  loginModes: "password"
  %{ endif }


  microsoft:
    enabled: false

  # Optional Okta SSO
  %{ if okta_sso_enabled }
  okta:
    enabled: ${okta_sso_enabled}
    issuer: ${okta_sso_issuer}
    redirectUri: https://${platform_domain}/backend/auth/oauth/okta/callback
    existingSecret:
      name: ${secret_provider_class_secret_name}
      clientIdKey: ${k8s_secret_key_okta_sso_client_id}
      clientSecretKey: ${k8s_secret_key_okta_sso_client_secret}
  %{ endif }

  %{ if google_sso_enabled }
  # Optional Google SSO
  google:
    enabled: ${google_sso_enabled}
    redirectUri: https://${platform_domain}/backend/auth/oauth/google/callback
    roleMapping: ${google_sso_role_mapping}
    existingSecret:
      name: ${secret_provider_class_secret_name}
      clientIdKey: ${k8s_secret_key_google_sso_client_id}
      clientSecretKey: ${k8s_secret_key_google_sso_client_secret}
  %{ endif }

  volumeMounts:
    - name: secrets-store
      mountPath: /mnt/secrets-store
      readOnly: true
  volumes:
    - name: secrets-store
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: ${secret_provider_class_name}
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/auth/$2"
      nginx.ingress.kubernetes.io/use-regex: "true"
      # ------------
      # Cert-manager issuer.
      # Remove this section if you're not using cert-manager for SSL certificates.
      cert-manager.io/cluster-issuer: letsencrypt
      # ------------
    enabled: true
    className: "nginx"
    hosts:
      - host: ${platform_domain}
        paths:
          - path: "/backend/auth(/|$)(.*)"
            pathType: Prefix
    tls:
      - secretName: nebuly-tls
        hosts:
          - ${platform_domain}

frontend:
  image:
    repository: "ghcr.io/nebuly-ai/nebuly-frontend"

  rootUrl: https://${platform_domain}
  backendApiUrl: https://${platform_domain}/backend
  authApiUrl: https://${platform_domain}/backend/auth
  ingress:
    enabled: true
    annotations:
      # ------------
      # Cert-manager issuer.
      # Remove this section if you're not using cert-manager for SSL certificates.
      cert-manager.io/cluster-issuer: letsencrypt
      # ------------
    className: "nginx"
    hosts:
      - host: ${platform_domain}
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: nebuly-tls
        hosts:
          - ${platform_domain}

openAi:
  enabled: true
  gpt4oDeployment: ${openai_gpt4o_deployment}
  endpoint: ${openai_endpoint}

  existingSecret:
    name: ${secret_provider_class_secret_name}
    apiKey: ${k8s_secret_key_openai_api_key}
